baseURL = "https://recca0120.github.io/"
title = "recca0120 技術筆記"
theme = "hugo-theme-stack"
languageCode = "zh-TW"
defaultContentLanguage = "zh-hant-tw"
hasCJKLanguage = true
timeZone = "Asia/Taipei"

[pagination]
  pagerSize = 10

[permalinks]
  post = "/:year/:month/:day/:slug/"
  page = "/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
