[goldmark]
  [goldmark.renderer]
    unsafe = true

[tableOfContents]
  endLevel = 4
  ordered = true
  startLevel = 2

[highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNos = true
  tabWidth = 4
