[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "分類"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "標籤"
  pageRef = "tags"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/recca0120"
  weight = 100
