[[main]]
  identifier = "home"
  name = "首頁"
  url = "/"
  weight = 10

  [main.params]
    icon = "home"

[[main]]
  identifier = "archives"
  name = "彙整"
  url = "/archives/"
  weight = 20

  [main.params]
    icon = "archives"

[[main]]
  identifier = "categories"
  name = "分類"
  url = "/categories/"
  weight = 30

  [main.params]
    icon = "categories"

[[main]]
  identifier = "tags"
  name = "標籤"
  url = "/tags/"
  weight = 40

  [main.params]
    icon = "tag"

[[main]]
  identifier = "search"
  name = "搜尋"
  url = "/search/"
  weight = 50

  [main.params]
    icon = "search"

[[social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/recca0120"

  [social.params]
    icon = "brand-github"

[[social]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"

  [social.params]
    icon = "rss"
