colorScheme = "slate"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/home.svg"
  showRecent = true
  showRecentItems = 12
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = true
  cardViewScreenWidth = true
  layoutBackgroundBlur = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 6
  showTaxonomies = true
  showWordCount = false
  sharingLinks = ["twitter", "reddit", "facebook", "email"]

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = true

[taxonomy]
  showTermCount = true
  showBreadcrumbs = false
  showTableOfContents = false
  cardView = false

[term]
  showBreadcrumbs = false
  showTableOfContents = false
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false
