mainSections = ["post"]
rssFullContent = true

[footer]
  since = 2020

[sidebar]
  subtitle = "Software Developer / 技術筆記"

[article]
  headingAnchor = true
  readingTime = true
  [article.license]
    enabled = false

[widgets]
  homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 20 } },
  ]
  page = [{ type = "toc" }]

[colorScheme]
  toggle = true
  default = "dark"

[comments]
  enabled = false
