mainSections = ["post"]
rssFullContent = true
favicon = "/favicon.ico"

[footer]
  since = 2020

[sidebar]
  subtitle = "Software Developer / 技術筆記"
  avatar = "img/avatar.png"
  emoji = "💻"

[article]
  headingAnchor = true
  readingTime = true
  math = true
  toc = true
  [article.license]
    enabled = true
    default = "Licensed under CC BY-SA 4.0"

[widgets]
  homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 20 } },
  ]
  page = [{ type = "toc" }]

[colorScheme]
  toggle = true
  default = "dark"

[comments]
  enabled = true
  provider = "giscus"

[comments.giscus]
  repo = "recca0120/recca0120.github.io"
  repoID = "MDEwOlJlcG9zaXRvcnk4MDE5MjAyMg=="
  category = "General"
  categoryID = "DIC_kwDOBMeiFs4C3jU4"
  mapping = "pathname"
  reactionsEnabled = 1
  emitMetadata = 0
  lightTheme = "light"
  darkTheme = "dark_tritanopia"
  lang = "zh-TW"
  inputPosition = "top"
  strict = 0
  loading = "lazy"

[opengraph]
  [opengraph.twitter]
    card = "summary_large_image"
