baseURL = "https://recca0120.github.io/"
title = "recca0120 技術筆記"
theme = "FixIt"
languageCode = "zh-TW"
defaultContentLanguage = "zh-tw"
hasCJKLanguage = true
timeZone = "Asia/Taipei"

[pagination]
  pagerSize = 10

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  version = "0.3.X"
  defaultTheme = "auto"
  dateFormat = "2006-01-02"

  [params.header]
    [params.header.title]
      name = "recca0120 技術筆記"

  [params.home]
    [params.home.profile]
      enable = true
      title = "recca0120"
      subtitle = "技術筆記"
      avatarURL = ""
      social = true
    [params.home.posts]
      enable = true
      paginate = 10

  [params.social]
    GitHub = "recca0120"

  [params.page]
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 50

  [params.footer]
    enable = true
    hugo = true
    author = true
    since = 2020

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "分類"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "標籤"
    url = "/tags/"
    weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]
